ARG PYTHON_BASE_IMAGE=3-slim-buster

FROM python:${PYTHON_BASE_IMAGE} AS build

ARG OCTOPRINT_REF 
ENV OCTOPRINT_REF ${OCTOPRINT_REF:-1.7.3}

RUN apt-get update \
  && apt-get install -y \
    build-essential \
    curl \
    ffmpeg \
  && apt-get clean 

RUN groupadd --gid 1000 octoprint \
  && useradd --uid 1000 --gid octoprint -G dialout --shell /bin/bash -m octoprint \
  && mkdir -p /octoprint/octoprint /octoprint/plugins \
  && chown -R root:root /octoprint \
  && chmod -R g+wrx /octoprint

COPY docker-entrypoint.sh /usr/local/bin

WORKDIR /home/octoprint

ENV PYTHONUSERBASE /octoprint/plugins
ENV PIP_USER true
ENV PATH "${PYTHONUSERBASE}/bin:${PATH}"

RUN	mkdir tmp && curl -fsSLO --compressed --retry 3 --retry-delay 10 \
  https://github.com/OctoPrint/OctoPrint/archive/${OCTOPRINT_REF}.tar.gz \
  && tar xzf ${OCTOPRINT_REF}.tar.gz --strip-components 1 -C tmp \
  && cd /home/octoprint/tmp \
  && pip install . \
  && rm -rf /home/octoprint/tmp

WORKDIR /octoprint
COPY config.yaml /octoprint/octoprint/config.yaml

EXPOSE 5000

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["octoprint", "--basedir", "/octoprint/octoprint", "serve"]
